# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hilbert_curve_3d_cpp <- function(level) {
    .Call('_SpaceFillingCurve_hilbert_curve_3d_cpp', PACKAGE = 'SpaceFillingCurve', level)
}

expand_by_rules_cpp <- function(rules, letters, code) {
    .Call('_SpaceFillingCurve_expand_by_rules_cpp', PACKAGE = 'SpaceFillingCurve', rules, letters, code)
}

int_to_binary <- function(x, len) {
    .Call('_SpaceFillingCurve_int_to_binary', PACKAGE = 'SpaceFillingCurve', x, len)
}

